# Generated by Django 2.1 on 2019-10-22 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ephemera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('message', models.TextField(max_length=200)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('site_title', models.TextField(max_length=100)),
                ('site_img', models.TextField(blank=True, default='ephemera/default.png', max_length=1000)),
                ('site_icon', models.TextField(blank=True, default='ephemera/default_icon.png', max_length=1000)),
                ('ep_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ep_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EphemeraURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='NGList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_user', to=settings.AUTH_USER_MODEL)),
                ('ng_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ng_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ephemera',
            name='site_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ephemeral.EphemeraURL'),
        ),
    ]
