# Generated by Django 2.1 on 2019-11-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ephemeral', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EphemeraDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.URLField()),
                ('post_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ephemera',
            name='site_icon',
            field=models.TextField(blank=True, default='static/ephemera/default_icon.png', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ephemera',
            name='site_img',
            field=models.TextField(blank=True, default='static/ephemera/default.png', max_length=1000),
        ),
    ]
